from direct.directnotify.DirectNotifyGlobal import directNotify
from game.toontown.parties.DistributedPartyCatchActivityAI import DistributedPartyCatchActivityAI

class DistributedPartyWinterCatchActivityAI(DistributedPartyCatchActivityAI):
    notify = directNotify.newCategory('DistributedPartyWinterCatchActivityAI')
