from direct.directnotify.DirectNotifyGlobal import directNotify
from game.toontown.parties.DistributedPartyTrampolineActivityAI import DistributedPartyTrampolineActivityAI

class DistributedPartyValentineTrampolineActivityAI(DistributedPartyTrampolineActivityAI):
    notify = directNotify.newCategory('DistributedPartyValentineTrampolineActivityAI')
