from direct.directnotify.DirectNotifyGlobal import directNotify
from game.toontown.parties.DistributedPartyTrampolineActivityAI import DistributedPartyTrampolineActivityAI

class DistributedPartyWinterTrampolineActivityAI(DistributedPartyTrampolineActivityAI):
    notify = directNotify.newCategory('DistributedPartyWinterTrampolineActivityAI')