from direct.directnotify.DirectNotifyGlobal import directNotify
from game.toontown.parties.DistributedPartyJukeboxActivityBaseAI import DistributedPartyJukeboxActivityBaseAI

class DistributedPartyValentineJukeboxActivityAI(DistributedPartyJukeboxActivityBaseAI):
    notify = directNotify.newCategory('DistributedPartyValentineJukeboxActivityAI')
