from direct.directnotify.DirectNotifyGlobal import directNotify
from game.toontown.ai.DistributedScavengerHuntTargetAI import DistributedScavengerHuntTargetAI

class DistributedWinterCarolingTargetAI(DistributedScavengerHuntTargetAI):
    notify = directNotify.newCategory('DistributedWinterCarolingTargetAI')